cart/urls.py
# cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('checkout/', views.checkout, name='checkout'),
    path('create-checkout-session/', views.create_checkout_session, name='create_checkout_session'),
    path('payment/success/', views.payment_success, name='payment_success'),
    path('payment/cancel/', views.payment_cancel, name='payment_cancel'),
]

products/urls.py
# products/urls.py
from django.urls import path
from .views import product_list


app_name = 'products'  # ✅ 加這一行，註冊 namespace

urlpatterns = [
    path('', product_list, name='product_list'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from login import views as login_views

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', login_views.index, name='index'),  
    path('login/', login_views.login, name='login'),
    path('register/', login_views.register, name='register'),
    path('logout/', login_views.logout, name='logout'),

    # Allauth URLs
    path('accounts/', include('allauth.urls')),
    
    # App URLs
    path('cart/', include('cart.urls')),
    path('products/', include('products.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)



if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

products/models.py
from django.db import models

class Product(models.Model):
    name = models.CharField(max_length=100)
    price = models.PositiveIntegerField()
    image = models.CharField(max_length=255)  # 圖片路徑
    quantity = models.PositiveIntegerField(default=1000)  # 🆕 新增庫存數量

    def __str__(self):
        return self.name

products/views.py
from django.shortcuts import render
from .models import Product

def product_list(request):
    products = Product.objects.all()
    return render(request, 'products/list.html', {'products': products})

templates/products/list.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="container">
  <h1 class="my-4">Product List</h1>
  <div class="row">
    {% for product in products %}
      <div class="col-lg-3 col-md-4 col-sm-6 mb-4">
        <div class="card h-100">
          <a href="#"><img class="card-img-top" src="/static/{{ product.image }}" alt="{{ product.name }}"></a>
          <div class="card-body">
            <h4 class="card-title">
              <a href="#">{{ product.name }}</a>
            </h4>
            <h5>${{ product.price }}</h5>
            <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!</p>
          </div>
          <div class="card-footer">
            <form action="{% url 'cart:cart_add' product.id %}" method="post">
              {% csrf_token %}
              <div class="input-group">
                <input type="number" name="quantity" value="1" min="1" max="{{ product.stock }}" class="form-control">
                <div class="input-group-append">
                  <button type="submit" class="btn btn-primary">Add to Cart</button>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    {% endfor %}
  </div>
</div>
{% endblock %}